config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users 
  resources :subs
  resource :session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint           not null, primary key
#  title       :string           not null
#  description :string
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Sub < ApplicationRecord
    validates :title, :user_id, presence: true

    belongs_to :moderator,
        foreign_key: :user_id,
        class_name: :User
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    before_validation :ensure_session_token

    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :session_token, presence: true, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true }

    attr_reader :password

    has_many :subs,
        class_name: :Sub,
        inverse_of: :moderator

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user&.is_password?(password)
            user
        else
            nil 
        end
    end

    def is_password?(password)
        BCrypt::Password.new(password_digest).is_password?(password)
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def reset_session_token!
        self.session_token = generate_unique_session_token
        save!
        self.session_token
    end

    private

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end

    def generate_unique_session_token
        loop do
            token = SecureRandom.urlsafe_base64 
            unless User.find_by(session_token: token)
                return token
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_user
    
    def current_user
        @current_user = User.find_by(session_token: session[:session_token])
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def logged_in?
        !!current_user
    end

    def logout
        current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to users_url if logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_in, only:[:destroy]
    before_action :require_logged_out, only:[:create, :new]

    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if user
            login(user)
            redirect_to users_url
        else
            flash.now[:errors] = ["Invalid login credentials"]
            @user = User.new(email: params[:user][:email])
            render :new
        end
    end

    def new
        @user = User.new
        render :new
    end

    def destroy
        logout
        redirect_to new_session_url
    end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_logged_in

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = Sub.new(sub_params)
        if @sub.save
            redirect_to subs_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def edit
        @sub = Sub.find(params[:id])
        render :edit
    end

    def update
        @sub = Sub.find_by(id: params[:id])
        if @sub&.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub ? @sub.errors.full_messages : ["Sub not found"]
            render :edit
        end
    end

    def show
        @sub = Sub.find(params[:id])
        render :show
    end

    def index
        @subs = Sub.all 
        render :index
    end

    private
    def sub_params
        params.require(:sub).permit(:title, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in, except:[:new, :create]

    def index
        @users = User.all
        render :index
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to users_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def new
        @user = User.new
        render :new
    end

    def destroy
    end
    
    def show
        @user = User.find(params[:id])
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <header>
    <div class="header-left">
      <img src="/assets/reddit-logo (1).png">
      <h1>Reddit</h1>
    </div>

    <div class="header-middle">
      <% unless logged_in? || current_page?(new_session_url) %>
        <form method="GET" action="<%= new_session_url %>">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="submit" value="Login">
        </form>
      <% end %>


      <% unless logged_in? || current_page?(new_user_url) %>
        <form method="GET" action="<%= new_user_url %>">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="submit" value="Sign Up">
        </form>
      <% end %>

      <% unless !logged_in? || current_page?(subs_url) %>
        <form method="GET" action="<%= subs_url %>">
          <input type="submit" value="View All Subs">
        </form>
      <% end %>

      <% unless !logged_in? || current_page?(users_url) %>
        <form method="GET" action="<%= users_url %>">
          <input type="submit" value="View All Users">
        </form>
      <% end %>
    </div>
    
    <div class="header-right">
      <% if logged_in? %>
        <form method="POST" action="<%= session_url %>">
          <input type="hidden" name="_method" value="DELETE">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="submit" value="Logout">
        </form>
      <% end %>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/edit.html.erb
<h1>Edit <%= @sub.title.capitalize %></h1>

<form method="POST" action="<%= sub_url %>">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="new-sub-title">Title</label>
    <input type="text" name="sub[title]" id="new-sub-title" value="<%= @sub.title %>">

    <label for="new-sub-description">Description</label>
    <textarea name="sub[description]" id="new-sub-description" placeholder="Your description here..."><%= @sub.description %></textarea>

    <input type="hidden" name="sub[user_id]" value="<%= current_user.id %>">

    <input type="submit" value="Edit Sub">
</form>

<% if flash.now[:errors] %>
    <% flash.now[:errors].each do |error| %>
        <%= error %>
    <% end %>
<% end %>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<% if @subs %>
    <% @subs.each do |sub| %>
        <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
    <% end %>
<% end %>

<form method="GET" action="<%= new_sub_url %>">
    <input type="submit" value="Create New Sub">
</form>

app/views/subs/new.html.erb
<h1>New Sub</h1>

<form method="POST" action="<%= subs_url %>">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="new-sub-title">Title</label>
    <input type="text" name="sub[title]" id="new-sub-title" value="<%= @sub.title %>">

    <label for="new-sub-description">Description</label>
    <textarea name="sub[description]" id="new-sub-description" placeholder="Your description here..."><%= @sub.description %></textarea>
    <input type="hidden" name="sub[user_id]" value="<%= current_user.id %>">

    <input type="submit" value="Create Sub">
</form>

<% if flash.now[:errors] %>
    <% flash.now[:errors].each do |error| %>
        <%= error %>
    <% end %>
<% end %>

app/views/subs/show.html.erb
<h1><%= @sub.title.capitalize %></h1>

<ul>
    <% if @sub.moderator %>
        <li>Moderator: <%= @sub.moderator.email %></li>
    <% end %>
    <li>Description: <%= @sub.description %></li>
    
    <li>** Posts Here**</li>
</ul>

<form method="GET" action="<%= edit_sub_url(@sub) %>">
    <input type="submit" value="Edit Sub">
</form>

app/views/users/index.html.erb
<h1>All Users</h1>

<% if @users %>
    <% @users.each do |user| %>
        <a href="<%= user_url(user) %>"><%= user.email %></a>
    <% end %>
<% end %>

<form method="GET" action="<%= new_user_url %>">
    <input type="submit" value="Create New User">
</form>

app/views/users/new.html.erb
<h1>Create User</h1>

<form method="POST" action="<%= users_url %>">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="create-user-email">Email</label>
    <input type="text" class="create-user-email" name="user[email]" value="<%= @user.email %>">

    <label for="create-user-password">Password</label>
    <input type="password" class="create-user-password" name="user[password]">

    <input type="submit" value="Create Account">
</form>

<% if flash.now[:errors] %>
    <% flash.now[:errors].each do |error| %>
        <%= error %>
    <% end %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<ul>
    <li><%= @user.email %></li>
</ul>

<% if @user.subs %>
    <h2>Subs</h2>
        <ul>
            <% @user.subs.each do |sub| %>
                <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
            <% end %>
        </ul>
<% end %>
<a href="<%= users_url %>">View all users</a>